routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::model('user', 'App\User');
Route::model('post', 'App\Action');

Route::bind('meal', function ($value) {
    return App\Meal::where('id', $value)->where('user_id', auth()->user()->id)->where('editable', 1)->firstOrFail();
});

Route::bind('target', function ($value) {
    return App\Target::where('id', $value)->where('user_id', auth()->user()->id)->firstOrFail();
});

Route::bind('training', function ($value) {
    return App\Training::where('id', $value)->where('editable', 1)->where('user_id', auth()->user()->id)->firstOrFail();
});

Route::group(['middleware' => ['auth', 'csrf', 'bindings', 'adminactions'], 'prefix' => 'profile'], function(){

    Route::get('/', 'ProfileController@index')->name('profile');
    Route::post('update', 'ProfileController@update')->name('profile.update');
    Route::get('settings', 'ProfileController@settings')->name('profile.settings');
    Route::resource('meals', 'MealsController', ['only' => ['index', 'create', 'store']]);
    Route::resource('posts', 'PostsController', ['except' => ['show', 'edit', 'update']]);
    Route::resource('trainings', 'TrainingsController', ['except' => ['show']]);
    Route::resource('targets', 'TargetsController', ['except' => ['show']]);
    Route::post('targets/reorder', 'TargetsController@reorder')->name('targets.reorder');
    Route::get('targets/{target}/toggle', 'TargetsController@toggle')->name('targets.toggle');
    Route::get('messages', 'MessagesController@index')->name('messages.index');
    Route::get('messages/{user}', 'MessagesController@conversation')->name('messages.conversation');
    Route::post('messages/{user}', 'MessagesController@send')->name('messages.send');
    
});

Route::group(['middleware' => ['bindings']], function(){
    
    Route::get('/user/{user}', 'IndexController@user')->name('index.user');
    Route::get('/', 'IndexController@index')->name('index');

});

Route::get('avatar/{avatar}', function($avatar){
    return response()->file(storage_path('app/public/avatars/'.$avatar));
})->where(['avatar' => '.*'])->name('avatar');

Route::get('wallpaper/{wallpaper}', function($wallpaper){
    return response()->file(storage_path('app/public/wallpaper/'.$wallpaper));
})->where(['wallpaper' => '.*'])->name('wallpaper');

Route::get('photo/{photo}', function($photo){
    return response()->file(storage_path('app/public/photos/'.$photo));
})->where(['photo' => '.*'])->name('photo');

Auth::routes();

app/Photo.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Carbon\Carbon;

class Photo extends Model
{
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'action_id', 'filename'
    ];
    
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];
    
    public function action() {
        return $this->belongsTo('\App\Action');
    }
    
    public function getUrlAttribute() {
        return route('photo', ['photo' => $this->filename]);
    }
    
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use \App\Action;

use \Auth;

use \App\Http\Requests\StoreActionRequest;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('posts.index')->with([
            'items' => auth()->user()->actions()->where('automat', 0)->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create')->with([
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreActionRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreActionRequest $request)
    {
        $input = $request->only(['content']);
        $input['automat'] = 0;
        $item = auth()->user()->actions()->create($input);


        foreach($request->file(['files']) as $upload)
        {
            $file = \Storage::putFile('public/photos', $upload);
            $item->photos()->create([
                'filename' => basename($file)
            ]);
        }
        return redirect()->route('posts.index')->with(['success' => 'Post został zapisany']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Action $item
     * @return \Illuminate\Http\Response
     */
    public function show($item)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Action $item
     * @return \Illuminate\Http\Response
     */
//    public function edit($item)
//    {
//        if($item->user_id !== auth()->user()->id)
//            return back();
//        
//        return view('posts.edit')->with([
//            'item' => $item,
//        ]);
//    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\StoreActionRequest  $request
     * @param  \App\Action $item
     * @return \Illuminate\Http\Response
     */
//    public function update(StoreActionRequest $request, $item)
//    {
//        $input = $request->only(['content']);
//        
//        $item->update($input);
//        return redirect()->route('posts.index')->with(['success' => 'Post został zaktualizowany']);
//    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Action $items
     * @return \Illuminate\Http\Response
     */
    public function destroy($item)
    {
        $item->delete();
        return redirect()->route('posts.index')->with(['success' => 'Post został usunięty']);
    }
}

resources/views/posts/create.blade.php
@extends('layouts.dashboard')

@section('view')
    <h2>Nowy post</h2>
    <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
        @include('posts.form', ['item' => NULL])
        <div class="row">
            <div class="col-xs-12 text-right" >
                @include('partials.forms.submit', ['text' => 'Zapisz'])
            </div>
        </div>
        
    </form>
@endsection

resources/views/posts/form.blade.php
{{ csrf_field() }}

<div id="create-post">
    <div class="row">
        <div class="col-xs-12">
            @include('partials.forms.textarea', ['item' => @$item, 'label' => 'Treść', 'option' => 'content', 'class' => "post-content"])
        </div>
        <div class="col-xs-12">
            @include('partials.forms.text', ['type' => 'file', 'item' => NULL, 'label' => 'Zdjęcia', 'option' => 'files[]', 'params' => ['multiple' => 'numtiple']])
        </div>
    </div>
</div>

resources/views/posts/index.blade.php
@extends('layouts.dashboard')

@section('view')
    <h2>Posty</h2>
    <div class="row">
        <div class="col-xs-12 text-right">
            <a href="{{ route('posts.create') }}" class="btn btn-primary">Dodaj</a>
        </div>
    </div>
    <table class="table table-sortable">
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($items as $item): ?>
                <tr data-id="{{ $item->id }}">
                    <td>
                        {{ $item->created_at->format('Y-m-d H:i:s') }}
                    </td>
                    <td>
                        <div class="post-lead">
                            {{ $item->lead }}
                            <?php if($item->automat): ?>
                                <span class="label label-default">automat</span>
                            <?php endif;?>
                        </div>
                    </td>
                    <td class="text-right">
                        <form action="{{ route('posts.destroy', ['post' => $item]) }}" method="POST">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <a href="#" class="btn btn-sm toggle-bottom-row">
                                <span class="glyphicon glyphicon-chevron-up glyphicon-chevron-down"></span>
                            </a>
                            @include('partials.forms.submit', ['text' => 'usuń', 'class' => 'btn-sm btn-danger'])
                        </form>
                    </td>
                </tr>
                <tr class="hidden warning" data-id="{{ $item->id }}">
                    <td></td>
                    <td colspan="2">
                        {{ $item->content }}
                        <div class="row">
                            <?php foreach($item->photos as $photo): ?>
                                <div class="col-md-3 col-sm-4 col-xs-6">
                                    <img src="{{ $photo->url }}" alt="{{ $photo->filename }}" class="img-responsive img-rounded">
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
@endsection