routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::model('user', 'App\User');
Route::model('post', 'App\Action');

Route::bind('meal', function ($value) {
    return App\Meal::where('id', $value)->where('user_id', auth()->user()->id)->where('editable', 1)->firstOrFail();
});

Route::bind('target', function ($value) {
    return App\Target::where('id', $value)->where('user_id', auth()->user()->id)->firstOrFail();
});

Route::bind('training', function ($value) {
    return App\Training::where('id', $value)->where('editable', 1)->where('user_id', auth()->user()->id)->firstOrFail();
});

Route::group(['middleware' => ['auth', 'csrf', 'bindings', 'adminactions'], 'prefix' => 'profile'], function(){

    Route::get('/', 'ProfileController@index')->name('profile');
    Route::post('update', 'ProfileController@update')->name('profile.update');
    Route::get('settings', 'ProfileController@settings')->name('profile.settings');
    Route::resource('meals', 'MealsController', ['only' => ['index', 'create', 'store']]);
    Route::resource('posts', 'PostsController', ['except' => ['show', 'edit', 'update']]);
    Route::resource('trainings', 'TrainingsController', ['except' => ['show']]);
    Route::resource('targets', 'TargetsController', ['except' => ['show']]);
    Route::post('targets/reorder', 'TargetsController@reorder')->name('targets.reorder');
    Route::get('targets/{target}/toggle', 'TargetsController@toggle')->name('targets.toggle');
    Route::get('messages', 'MessagesController@index')->name('messages.index');
    Route::get('messages/{user}', 'MessagesController@conversation')->name('messages.conversation');
    Route::post('messages/{user}', 'MessagesController@send')->name('messages.send');
    
});

Route::group(['middleware' => ['bindings']], function(){
    
    Route::get('/user/{user}', 'IndexController@user')->name('index.user');
    Route::get('/', 'IndexController@index')->name('index');

});

Route::get('avatar/{avatar}', function($avatar){
    return response()->file(storage_path('app/public/avatars/'.$avatar));
})->where(['avatar' => '.*'])->name('avatar');

Route::get('wallpaper/{wallpaper}', function($wallpaper){
    return response()->file(storage_path('app/public/wallpaper/'.$wallpaper));
})->where(['wallpaper' => '.*'])->name('wallpaper');

Route::get('photo/{photo}', function($photo){
    return response()->file(storage_path('app/public/photos/'.$photo));
})->where(['photo' => '.*'])->name('photo');

Auth::routes();

app/Target.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use \Carbon\Carbon;

class Target extends Model
{
    
    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('position', function (Builder $builder) {
            $builder->orderBy('position', 'ASC');
        });
    }
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'deadline', 'weight', 'difference', 'daily_info', 'daily_burnout', 'activated_at', 'start_weight'
    ];
    
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];
    
    /**
     * Fieldsto be casted for Carbon dates
     *
     * @var array
     */
    protected $dates = [
        'created_at', 'updated_at', 'deadline'
    ];
    
    public function user() 
    {
        return $this->belongsTo('\App\User');
    }
    
    public function getBurnoutAttribute() 
    {
        return $this->difference * \App\Algorithm::KCAL_PER_KG;
    }
    
    public function getDurationAttribute() 
    {
        return $this->created_at->diffInDays($this->deadline);
    }
//    
//    public function getDailyBurnoutAttribute() 
//    {
//        return round($this->burnout/$this->duration);
//    }
    
    public function getIsPastAttribute() 
    {
        return Carbon::now() >= $this->deadlione;
    }
    
    public function activate($message = TRUE) 
    {
        
        $this->active = 1;
        $this->finished = 0;
        $this->activated_at = Carbon::now();
        $this->start_weight = auth()->user()->weight;
        $this->difference = $this->user->weight - $this->weight;
        $this->daily_burnout = round($this->burnout / $this->duration);
        $this->save();
        
        if($message)
        {
            $this->user->actions()->create([
                'content' => 'Nowy cel: '.$this->name
            ]);
        }
        
    }
    
    public function deactivate($message = TRUE) 
    {
        $this->active = 0;
        $this->finished = 0;
        $this->activated_at = NULL;
        $this->start_weight = 0;
        $this->daily_burnout = 0; //kcal
        $this->difference = 0;
        $this->save();
        
        if($message)
        {
            $this->user->actions()->create([
                'content' => 'Usunięcie celu'
            ]);
        }
    }
    
}

app/Http/Controllers/TargetsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use \App\Target;

use \Auth;

use \App\Http\Requests\StoreTargetRequest;

class TargetsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('targets.index')->with([
            'items' => auth()->user()->targets
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('targets.create')->with([
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreTargetRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTargetRequest $request)
    {
        $input = $request->only(['name', 'description', 'weight', 'deadline']);
        auth()->user()->targets()->create($input);
        return redirect()->route('targets.index')->with(['success' => 'Cel został dodany']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Target $item
     * @return \Illuminate\Http\Response
     */
    public function show($item)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Target $item
     * @return \Illuminate\Http\Response
     */
    public function edit($item)
    {
        if($item->user_id !== auth()->user()->id)
            return back();
        
        return view('targets.edit')->with([
            'item' => $item,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\StoreTargetRequest  $request
     * @param  \App\Target $item
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTargetRequest $request, $item)
    {
        $input = $request->only(['name', 'description', 'weight', 'deadline']);
        
        $item->update($input);
        return redirect()->route('targets.index')->with(['success' => 'Cel został zaktualiwany']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Target $items
     * @return \Illuminate\Http\Response
     */
    public function destroy($item)
    {
        $item->delete();
        return redirect()->route('targets.index')->with(['success' => 'Cel został usunięty']);
    }
    
    public function reorder(Request $request)
    {
        foreach($request->input('order') as $order => $id)
            Target::where('id', $id)->update(['position' => $order]);
        die;
    }
    
    public function toggle(Request $request, $item)
    {
        foreach(auth()->user()->targets as $target)
            $target->deactivate(FALSE);
        
        $item->active ? $item->deactivate() : $item->activate();
        
        return back();
    }
}

resources/views/targets/create.blade.php
@extends('layouts.dashboard')

@section('view')
    <h2>Nowy cel</h2>
    <form action="{{ route('targets.store') }}" method="POST">
        @include('targets.form', ['item' => NULL])
        <div class="row">
            <div class="col-xs-12 text-right" >
                @include('partials.forms.submit', ['text' => 'Zapisz'])
            </div>
        </div>
        
    </form>
@endsection

resources/views/targets/edit.blade.php
@extends('layouts.dashboard')

@section('view')
    <h2>Zmień cel</h2>
    <form action="{{ route('targets.update', ['target' => $item]) }}" method="POST">
        @include('targets.form', ['item' => $item])
        {{ method_field('PATCH') }}
        <div class="row">
            <div class="col-xs-12 text-right" >
                @include('partials.forms.submit', ['text' => 'Zaktualizuj'])
            </div>
        </div>
        
    </form>
@endsection

resources/views/targets/form.blade.php
{{ csrf_field() }}
<div class="row">
    <div class="col-sm-6 col-xs-12">
        @include('partials.forms.text', ['item' => @$item, 'label' => 'Nazwa', 'option' => 'name'])
    </div>
    <div class="col-sm-6 col-xs-12">
        @include('partials.forms.text', ['type' => 'number', 'item' => @$item, 'label' => 'Docelowa waga', 'option' => 'weight'])
    </div>
    <div class="col-sm-6 col-xs-12">
        @include('partials.forms.datepicker', ['type' => 'text', 'item' => @$item, 'label' => 'Do kiedy', 'option' => 'deadline'])
    </div>
    <div class="col-sm-6 col-xs-12">
        @include('partials.forms.textarea', ['item' => @$item, 'label' => 'Opis', 'option' => 'description'])
    </div>
</div>

resources/views/targets/index.blade.php
@extends('layouts.dashboard')

@section('view')
    {{ csrf_field() }}
    <h2>Cele</h2>
    <div class="row">
        <div class="col-xs-12 text-right">
            <a href="{{ route('targets.create') }}" class="btn btn-primary">Dodaj</a>
        </div>
    </div>
    <table class="table table-sortable">
        <thead>
            <tr>
                <th></th>  <th></th>
                <th>Nazwa</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($items as $item): ?>
                <tr data-id="{{ $item->id }}">
                    <td>
                        <div class="btn btn-xs">
                            <span class="glyphicon glyphicon-menu-hamburger"></span>
                        </div>
                    </td>
                    <td>{{ $item->deadline->format('Y-m-d') }}</td>
                    <td>{{ $item->name }}</td>
                    <td class="text-right">
                        <form action="{{ route('targets.destroy', ['target' => $item]) }}" method="POST">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <a href="{{ route('targets.toggle', ['target' => $item]) }}" class="btn btn-success {{ $item->active ? '' : 'btn-outline' }} btn-sm">
                                <span class="glyphicon glyphicon-ok"></span>
                            </a>
                            <?php if(!$item->active): ?>
                                <a href="{{ route('targets.edit', ['target' => $item]) }}" class="btn btn-primary btn-sm">edytuj</a>
                                @include('partials.forms.submit', ['text' => 'usuń', 'class' => 'btn-sm btn-danger'])
                            <?php endif; ?>
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

@endsection