routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::model('user', 'App\User');
Route::model('post', 'App\Action');

Route::bind('meal', function ($value) {
    return App\Meal::where('id', $value)->where('user_id', auth()->user()->id)->where('editable', 1)->firstOrFail();
});

Route::bind('target', function ($value) {
    return App\Target::where('id', $value)->where('user_id', auth()->user()->id)->firstOrFail();
});

Route::bind('training', function ($value) {
    return App\Training::where('id', $value)->where('editable', 1)->where('user_id', auth()->user()->id)->firstOrFail();
});

Route::group(['middleware' => ['auth', 'csrf', 'bindings', 'adminactions'], 'prefix' => 'profile'], function(){

    Route::get('/', 'ProfileController@index')->name('profile');
    Route::post('update', 'ProfileController@update')->name('profile.update');
    Route::get('settings', 'ProfileController@settings')->name('profile.settings');
    Route::resource('meals', 'MealsController', ['only' => ['index', 'create', 'store']]);
    Route::resource('posts', 'PostsController', ['except' => ['show', 'edit', 'update']]);
    Route::resource('trainings', 'TrainingsController', ['except' => ['show']]);
    Route::resource('targets', 'TargetsController', ['except' => ['show']]);
    Route::post('targets/reorder', 'TargetsController@reorder')->name('targets.reorder');
    Route::get('targets/{target}/toggle', 'TargetsController@toggle')->name('targets.toggle');
    Route::get('messages', 'MessagesController@index')->name('messages.index');
    Route::get('messages/{user}', 'MessagesController@conversation')->name('messages.conversation');
    Route::post('messages/{user}', 'MessagesController@send')->name('messages.send');
    
});

Route::group(['middleware' => ['bindings']], function(){
    
    Route::get('/user/{user}', 'IndexController@user')->name('index.user');
    Route::get('/', 'IndexController@index')->name('index');

});

Route::get('avatar/{avatar}', function($avatar){
    return response()->file(storage_path('app/public/avatars/'.$avatar));
})->where(['avatar' => '.*'])->name('avatar');

Route::get('wallpaper/{wallpaper}', function($wallpaper){
    return response()->file(storage_path('app/public/wallpaper/'.$wallpaper));
})->where(['wallpaper' => '.*'])->name('wallpaper');

Route::get('photo/{photo}', function($photo){
    return response()->file(storage_path('app/public/photos/'.$photo));
})->where(['photo' => '.*'])->name('photo');

Auth::routes();

app/Training.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

use Carbon\Carbon;

class Training extends Model
{
    
    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('order', function (Builder $builder) {
            $builder->orderBy('created_at', 'DESC');
        });
    }
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'description', 'sport_id', 'duration', 'kcal'
    ];
    
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];
    
    /**
     * Fieldsto be casted for Carbon dates
     *
     * @var array
     */
    protected $dates = [
        'created_at', 'updated_at',
    ];
    
    public function user() {
        return $this->belongsTo('\App\User');
    }
    
    public function sport() {
        return $this->belongsTo('\App\Sport');
    }
    
    public function getDurationTextAttribute(){
        $carbon = Carbon::createFromTimestamp($this->duration*60);        
        return $carbon->format("H:i \h");
    }
    
    public function getKcalTextAttribute(){
        return $this->kcal . ' kcal';
    }
    
}

app/Http/Controllers/TrainingsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use \App\Training;

use \Auth;

use \App\Http\Requests\StoreTrainingRequest;

class TrainingsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('trainings.index')->with([
            'items' => auth()->user()->trainings
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('trainings.create')->with([
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreTrainingRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTrainingRequest $request)
    {
        $input = $request->only(['sport_id', 'duration', 'description']);
        auth()->user()->trainings()->create($input);
        return redirect()->route('trainings.index')->with(['success' => 'Trening zapisano. Możesz go edytować póki nie zmienisz parametrów ciała']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Target $item
     * @return \Illuminate\Http\Response
     */
    public function show($item)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Target $item
     * @return \Illuminate\Http\Response
     */
    public function edit($item)
    {
        if($item->user_id !== auth()->user()->id)
            return back();
        
        return view('trainings.edit')->with([
            'item' => $item,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\StoreTrainingRequest  $request
     * @param  \App\Training $item
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTrainingRequest $request, $item)
    {
        $input = $request->only(['sport_id', 'description', 'duration']);
        $item->update($input);
        return redirect()->route('trainings.index')->with(['success' => 'Trening został zaktualiwany']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Training $item
     * @return \Illuminate\Http\Response
     */
    public function destroy($item)
    {
        $item->delete();
        return redirect()->route('trainings.index')->with(['success' => 'Trening został wycofany']);
    }
    
    public function reorder(Request $request)
    {
        foreach($request->input('order') as $order => $id)
            Target::where('id', $id)->update(['position' => $order]);
        die;
    }
    
    public function toggle(Request $request, $item)
    {
        $item->active = (int)!$item->active;
        $item->save();
        return back();
    }
}

resources/views/trainings/create.blade.php
@extends('layouts.dashboard')

@section('view')
    <h2>Nowy trening</h2>
    <form action="{{ route('trainings.store') }}" method="POST">
        @include('trainings.form', ['item' => NULL])
        <div class="row">
            <div class="col-xs-12 text-right" >
                @include('partials.forms.submit', ['text' => 'Zapisz'])
            </div>
        </div>
        
    </form>
@endsection

resources/views/trainings/edit.blade.php
@extends('layouts.dashboard')

@section('view')
    <h2>Zmień trening</h2>
    <form action="{{ route('trainings.update', ['training' => $item]) }}" method="POST">
        @include('trainings.form', ['item' => $item])
        {{ method_field('PATCH') }}
        <div class="row">
            <div class="col-xs-12 text-right" >
                @include('partials.forms.submit', ['text' => 'Zaktualizuj'])
            </div>
        </div>
        
    </form>
@endsection

resources/views/trainings/form.blade.php
{{ csrf_field() }}
<div class="row">
    <div class="col-xs-6">
        @include('partials.forms.select', ['item' => @$item, 'label' => 'Sport', 'option' => 'sport_id', 'source' => $sports])
    </div>
    <div class="col-xs-6">
        @include('partials.forms.text', ['item' => @$item, 'label' => 'Czas trwania (minuty)', 'option' => 'duration'])
    </div>
    <div class="col-xs-12">
        @include('partials.forms.textarea', ['item' => @$item, 'label' => 'Opis', 'option' => 'description'])
    </div>
</div>

resources/views/trainings/index.blade.php
@extends('layouts.dashboard')

@section('view')
    {{ csrf_field() }}
    <h2>Twoje treningi</h2>
    <div class="row">
        <div class="col-xs-12 text-right">
            <a href="{{ route('trainings.create') }}" class="btn btn-primary">Dodaj</a>
        </div>
    </div>
    <table class="table table-sortable">
        <tbody>
            <?php $last = ''; ?>
            <?php foreach($items as $item): ?>
                <?php $formatted =  $item->created_at->format('Y-m-d'); ?>
                <?php if($last !== $formatted): ?>
                <?php $last = $formatted; ?>
                    <tr>
                        <td class="warning" colspan="5">
                            <strong>
                                {{ $formatted }}
                            </strong>
                        </td>
                    </tr>
                <?php endif; ?>
                <tr>
                    <td>
                        {{ $item->created_at->format('H:i') }}
                    </td>
                    <td>{{ $item->sport->name }}</td>
                    <td><i class="glyphicon glyphicon-time"></i> {{ $item->duration_text }}</td>
                    <td>{{ $item->kcal_text }}</td>
                    <td class="text-right">
                        <form action="{{ route('trainings.destroy', ['training' => $item]) }}" method="POST">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <?php if($item->editable): ?>
                                <a href="{{ route('trainings.edit', ['target' => $item]) }}" class="btn btn-primary btn-sm">edytuj</a>
                                @include('partials.forms.submit', ['text' => 'usuń', 'class' => 'btn-sm btn-danger'])
                            <?php endif; ?>
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    


@endsection