routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::model('user', 'App\User');
Route::model('post', 'App\Action');

Route::bind('meal', function ($value) {
    return App\Meal::where('id', $value)->where('user_id', auth()->user()->id)->where('editable', 1)->firstOrFail();
});

Route::bind('target', function ($value) {
    return App\Target::where('id', $value)->where('user_id', auth()->user()->id)->firstOrFail();
});

Route::bind('training', function ($value) {
    return App\Training::where('id', $value)->where('editable', 1)->where('user_id', auth()->user()->id)->firstOrFail();
});

Route::group(['middleware' => ['auth', 'csrf', 'bindings', 'adminactions'], 'prefix' => 'profile'], function(){

    Route::get('/', 'ProfileController@index')->name('profile');
    Route::post('update', 'ProfileController@update')->name('profile.update');
    Route::get('settings', 'ProfileController@settings')->name('profile.settings');
    Route::resource('meals', 'MealsController', ['only' => ['index', 'create', 'store']]);
    Route::resource('posts', 'PostsController', ['except' => ['show', 'edit', 'update']]);
    Route::resource('trainings', 'TrainingsController', ['except' => ['show']]);
    Route::resource('targets', 'TargetsController', ['except' => ['show']]);
    Route::post('targets/reorder', 'TargetsController@reorder')->name('targets.reorder');
    Route::get('targets/{target}/toggle', 'TargetsController@toggle')->name('targets.toggle');
    Route::get('messages', 'MessagesController@index')->name('messages.index');
    Route::get('messages/{user}', 'MessagesController@conversation')->name('messages.conversation');
    Route::post('messages/{user}', 'MessagesController@send')->name('messages.send');
    
});

Route::group(['middleware' => ['bindings']], function(){
    
    Route::get('/user/{user}', 'IndexController@user')->name('index.user');
    Route::get('/', 'IndexController@index')->name('index');

});

Route::get('avatar/{avatar}', function($avatar){
    return response()->file(storage_path('app/public/avatars/'.$avatar));
})->where(['avatar' => '.*'])->name('avatar');

Route::get('wallpaper/{wallpaper}', function($wallpaper){
    return response()->file(storage_path('app/public/wallpaper/'.$wallpaper));
})->where(['wallpaper' => '.*'])->name('wallpaper');

Route::get('photo/{photo}', function($photo){
    return response()->file(storage_path('app/public/photos/'.$photo));
})->where(['photo' => '.*'])->name('photo');

Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

use \Carbon\Carbon;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'login', 'email', 'password', 'name', 'lastname', 'last_logged', 'active', 'height','weight','year','gender'
    ];
    
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
    /**
     * Fieldsto be casted for Carbon dates
     *
     * @var array
     */
    protected $dates = [
        'created_at', 'updated_at', 'last_logged',
    ];
    
    public function getRouteKeyName()
    {
        return 'id';
    }
    
    /**
     * Messages of this user
     * 
     * @return App\Message
     */
    public function messages() 
    { 
        return $this->hasMany('App\Message');
    }
    
    /**
     * Correspondents
     * 
     * @return App\Message
     */
    public function conversations() 
    {
        return $this->hasMany('App\Message')->distinct()->orderBy('created_at', 'DESC')->groupBy('recipient_id');
    }
    
    /**
     * 
     * 
     * @return App\Message
     */
    public function messagesOf($correspondent) 
    {
        return $this->hasMany('App\Message')->where('recipient_id', $correspondent->id)->orWhere(function($query) use($correspondent) {
            $query->where('user_id', $correspondent->id)->where('recipient_id', auth()->user()->id);
        })->orderBy('created_at', 'ASC');
    }
    
    /**
     * Trainings of this user
     * 
     * @return App\Training
     */
    public function trainings() 
    { 
        return $this->hasMany('App\Training')->orderBy('created_at', 'DESC');
    }
    
    /**
     * Targets of this user
     * 
     * @return App\Target
     */
    public function targets() 
    { 
        return $this->hasMany('App\Target');
    }
    
    public function current_target() 
    { 
        return $this->hasOne('App\Target')->where('active', 1);
    }
    
    /**
     * Meals of this user
     * 
     * @return App\Meal
     */
    public function meals() 
    { 
        return $this->hasMany('App\Meal')->orderBy('created_at', 'DESC');
    }
    
    /**
     * Actions messages of this user
     * 
     * @return App\Action
     */
    public function actions() 
    { 
        return $this->hasMany('App\Action')->orderBy('created_at', 'DESC');
    }
    
    public function getAvatarAttribute()
    {
        $files = [
                'avatars/'.$this->id.'.jpg', 
                'avatars/'.$this->id.'.jpeg', 
                'avatars/'.$this->id.'.png', 
            ];
        
        foreach($files as $file)
            if(\Storage::disk('public')->exists($file))
                return route('avatar', ['avatar' => basename($file)]);
        
        return '/assets/images/user_'.($this->gender ? '' : 'fe').'male.png';
    }
    
    public function getWallpaperAttribute()
    {
        $files = [
                'wallpaper/'.$this->id.'.jpg', 
                'wallpaper/'.$this->id.'.jpeg', 
                'wallpaper/'.$this->id.'.png', 
            ];
        
        foreach($files as $file)
            if(\Storage::disk('public')->exists($file))
                return route('wallpaper', ['wallpaper' => basename($file)]);
        
        return '';
    }
    
    public function getFullNameAttribute()
    {
        return implode(' ', [$this->name, $this->lastname]);
    }
    
    public function getAnonymusNameAttribute()
    {
        return implode(' ', [$this->name, substr($this->lastname, 0, 1)]);
    }
    
    public function getAgeAttribute()
    {
        return (new \Carbon\Carbon)->format('Y') - $this->year;
    }
    
    public function getBmiAttribute()
    {
        return number_format($this->weight / pow($this->height / 100, 2), 2);
    }
    
    public function getBmiStateAttribute()
    {
        if($this->bmi < 18.5)
            return -1;
        elseif($this->bmi > 25)
            return 1;
        return 0;
    }
    
    public function getDailyKcalAttribute()
    {
        if ($this->gender == 0) // woman
            return (665.151 + (9.567 * $this->weight) + (1.85 * $this->height) - (4.68 * $this->age)) * 1.75;
        else // man
            return (66.47 + (13.7 * $this->weight) + (5.0 * $this->height) - (6.76 * $this->age)) * 1.75;
        
        return 0;
    }
    
    public static function genders() {
        return ['Kobieta', 'Mężczyzna'];
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <link href="/assets/css/style.css?t={{ time() }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
			    <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        Health & fitness
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Logowanie</a></li>
                            <li><a href="{{ url('/register') }}">Rejestracja</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->full_name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('profile') }}">
                                            Panel
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Wyloguj
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/assets/js/jquery-2.1.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/locale/pl.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/bootstrap-datetimepicker.js"></script>
    <script src="/assets/js/jquery.sortable.min.js"></script>
    <script src="/assets/js/main.js"></script>
</body>
</html>

resources/views/layouts/dashboard.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div id="dashboard-menu">
                    <div class="panel panel-default panel-user">
                        <div class="panel-heading">{{ $user->login }}</div>
                        <div id="avatar" style="background-image:url('{{ $user->avatar }}')"></div>
                        <div class="panel-body">
                            <p>waga: <strong>{{ $user->weight }}</strong> {{ $user->wunit }}</p>
                            <p>wzrost: <strong>{{ $user->height }}</strong> {{ $user->hunit }}</p>
                            <p>BMI: <strong>{{ $user->bmi }}</strong>
                                <?php if($user->bmi_state === -1): ?>
									<font color="yellow">(niedowaga)</font>
                                <?php elseif($user->bmi_state === 0): ?>
                                    <font color="green">(waga prawidłowa)</font>
                                <?php elseif($user->bmi_state === 1): ?>
                                    <font color="red">(nadwaga)</font>
                                <?php endif; ?>
                            </p>
                            <p>wiek: <strong>{{ $user->age }}</strong></p>
                        </div>
                    </div>
                    <ul class="nav nav-pills nav-stacked">
                        <li role="presentation" class="{{ request()->is('profile') ? 'active' : '' }}">
                            <a href="{{ route('profile') }}">Strona główna panelu</a>
                        </li>
                        <li role="presentation" class="{{ request()->is('profile/targets*') ? 'active' : '' }}">
                            <a href="{{ route('targets.index') }}">Cele</a>
                        </li>
                        <li role="presentation" class="{{ request()->is('profile/trainings*') ? 'active' : '' }}">
                            <a href="{{ route('trainings.index') }}">Treningi</a>
                        </li>
                        <li role="presentation" class="{{ request()->is('profile/meals*') ? 'active' : '' }}">
                            <a href="{{ route('meals.index') }}">Dieta</a>
                        </li>
                        <li role="presentation" class="{{ request()->is('profile/messages*') ? 'active' : '' }}">
						
							<a href="{{ route('messages.index') }}">Wiadomości <!--<span class="badge">{{ auth()->user()->messagesOf($user)->count() }}</span> -->
							</a>
							
						</li>
                        <li role="presentation" class="{{ request()->is('posts*') ? 'active' : '' }}">
                            <a href="{{ route('posts.index') }}">Posty</a>
                        </li>
                        <li role="presentation" class="{{ request()->is('profile/settings*') ? 'active' : '' }}">
                            <a href="{{ route('profile.settings') }}">Ustawienia</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-9 col-sm-8 col-xs-12">
                @include('partials.errors')
                @yield('view')
            </div>
        </div>
    </div>
@endsection